
POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "Pedrinho",
    "email": "Pedrinho@email.com",
    "password": "1223145153"
}

###
GET http://localhost:3003/user/get

###
POST http://localhost:3003/post/create 
Content-Type: application/json 

{
    "photo": "https://th.bing.com/th/id/OIP.2s6v8hFMcJDkWqc-Un3M8QHaFj?pid=ImgDet&rs=1",
    "description": "Paisagem pega na net!",
    "type": "normal",
    "created_at": "2022-05-16",
    "author_id": "b1cbc1d2-a520-40d7-bade-9b740bfc9005"
}

###
GET http://localhost:3003/post/get
